site_name: Skeleplex

nav:
- Home: index.md
- Code Reference: reference/

theme:
  name: material
  features:
  - search.highlight
  - search.suggest
  - content.code.copy
  - content.code.annotate
  # - navigation.indexes
  # - navigation.footer
  # - navigation.sections
  - toc.follow

plugins:
- search  
- gen-files:
    scripts:
    - scripts/gen_ref_pages.py  
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mkdocstrings:
    handlers:
      python:
        import:
          - https://docs.python.org/3/objects.inv
          - https://numpy.org/doc/stable/objects.inv
        options:
          docstring_section_style: list
          docstring_style: "numpy"
          filters: ["!^_"]
          heading_level: 1
          inherited_members: true
          merge_init_into_class: true
          parameter_headings: true
          relative_crossrefs: true
          scoped_crossrefs: true
          separate_signature: true
          # show_bases: false
          show_inheritance_diagram: true
          show_root_heading: true
          # show_root_full_path: false
          show_signature_annotations: true
          # show_source: false
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          signature_crossrefs: true
          summary: true
          unwrap_annotated: true