name: docs 
on:
  push:
    branches:
      - master 
      - main
    tags:
    - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
        branches:
          - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install Package
        run: |
          python -m pip install -U pip
          # if running a cron job, we add the --pre flag to test against pre-releases
          python -m pip install .[test] ${{ github.event_name == 'schedule' && '--pre' || ''  }}
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material mkdocstrings-python mkdocs-literate-nav mkdocs-gen-files mkdocs-section-index
      - name: test build docs
        if: github.event_name == 'pull_request'
        run: mkdocs build
      - name: deploy docs
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: mkdocs gh-deploy --force